/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, UserFile as PrismaUserFile } from "@prisma/client";

export class UserFileServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.UserFileCountArgs, "select">): Promise<number> {
    return this.prisma.userFile.count(args);
  }

  async userFiles(
    args: Prisma.UserFileFindManyArgs
  ): Promise<PrismaUserFile[]> {
    return this.prisma.userFile.findMany(args);
  }
  async userFile(
    args: Prisma.UserFileFindUniqueArgs
  ): Promise<PrismaUserFile | null> {
    return this.prisma.userFile.findUnique(args);
  }
  async createUserFile(
    args: Prisma.UserFileCreateArgs
  ): Promise<PrismaUserFile> {
    return this.prisma.userFile.create(args);
  }
  async updateUserFile(
    args: Prisma.UserFileUpdateArgs
  ): Promise<PrismaUserFile> {
    return this.prisma.userFile.update(args);
  }
  async deleteUserFile(
    args: Prisma.UserFileDeleteArgs
  ): Promise<PrismaUserFile> {
    return this.prisma.userFile.delete(args);
  }
}
