/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { UserFile } from "./UserFile";
import { UserFileCountArgs } from "./UserFileCountArgs";
import { UserFileFindManyArgs } from "./UserFileFindManyArgs";
import { UserFileFindUniqueArgs } from "./UserFileFindUniqueArgs";
import { CreateUserFileArgs } from "./CreateUserFileArgs";
import { UpdateUserFileArgs } from "./UpdateUserFileArgs";
import { DeleteUserFileArgs } from "./DeleteUserFileArgs";
import { UserFileService } from "../userFile.service";
@graphql.Resolver(() => UserFile)
export class UserFileResolverBase {
  constructor(protected readonly service: UserFileService) {}

  async _userFilesMeta(
    @graphql.Args() args: UserFileCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [UserFile])
  async userFiles(
    @graphql.Args() args: UserFileFindManyArgs
  ): Promise<UserFile[]> {
    return this.service.userFiles(args);
  }

  @graphql.Query(() => UserFile, { nullable: true })
  async userFile(
    @graphql.Args() args: UserFileFindUniqueArgs
  ): Promise<UserFile | null> {
    const result = await this.service.userFile(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => UserFile)
  async createUserFile(
    @graphql.Args() args: CreateUserFileArgs
  ): Promise<UserFile> {
    return await this.service.createUserFile({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => UserFile)
  async updateUserFile(
    @graphql.Args() args: UpdateUserFileArgs
  ): Promise<UserFile | null> {
    try {
      return await this.service.updateUserFile({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => UserFile)
  async deleteUserFile(
    @graphql.Args() args: DeleteUserFileArgs
  ): Promise<UserFile | null> {
    try {
      return await this.service.deleteUserFile(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
