/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UserFileService } from "../userFile.service";
import { UserFileCreateInput } from "./UserFileCreateInput";
import { UserFile } from "./UserFile";
import { UserFileFindManyArgs } from "./UserFileFindManyArgs";
import { UserFileWhereUniqueInput } from "./UserFileWhereUniqueInput";
import { UserFileUpdateInput } from "./UserFileUpdateInput";

export class UserFileControllerBase {
  constructor(protected readonly service: UserFileService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: UserFile })
  async createUserFile(
    @common.Body() data: UserFileCreateInput
  ): Promise<UserFile> {
    return await this.service.createUserFile({
      data: data,
      select: {
        adhaar: true,
        createdAt: true,
        id: true,
        panCard: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [UserFile] })
  @ApiNestedQuery(UserFileFindManyArgs)
  async userFiles(@common.Req() request: Request): Promise<UserFile[]> {
    const args = plainToClass(UserFileFindManyArgs, request.query);
    return this.service.userFiles({
      ...args,
      select: {
        adhaar: true,
        createdAt: true,
        id: true,
        panCard: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: UserFile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async userFile(
    @common.Param() params: UserFileWhereUniqueInput
  ): Promise<UserFile | null> {
    const result = await this.service.userFile({
      where: params,
      select: {
        adhaar: true,
        createdAt: true,
        id: true,
        panCard: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: UserFile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUserFile(
    @common.Param() params: UserFileWhereUniqueInput,
    @common.Body() data: UserFileUpdateInput
  ): Promise<UserFile | null> {
    try {
      return await this.service.updateUserFile({
        where: params,
        data: data,
        select: {
          adhaar: true,
          createdAt: true,
          id: true,
          panCard: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: UserFile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUserFile(
    @common.Param() params: UserFileWhereUniqueInput
  ): Promise<UserFile | null> {
    try {
      return await this.service.deleteUserFile({
        where: params,
        select: {
          adhaar: true,
          createdAt: true,
          id: true,
          panCard: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
